/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.property;

import swing.SliderGradient;
import swing.ToggleAdapter;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashSet;
import java.util.Iterator;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {
    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    Statement st;

    public static int Lease_id =500;
    public String date = "2023-05-18";
    
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        conn = JavaConnect.ConnectDB();
        
        
      
        toggleButton1.addEventToggleSelected(new ToggleAdapter(){
        public void onSelected(boolean selected){
           /* if(selected){
            System.out.println("SELECETED");
            }
                else{
                System.out.println("HEKKi");

            }*/
        }
        
        });
         toggleButton2.addEventToggleSelected(new ToggleAdapter(){
        public void onSelected(boolean selected){
          /*  if(selected){
            System.out.println("SELECETED");
            }
                else{
                System.out.println("HEKKi");

            }*/
        }
        });
          toggleButton3.addEventToggleSelected(new ToggleAdapter(){
        public void onSelected(boolean selected){
          /*  if(selected){
            System.out.println("SELECETED");
            }
                else{
                System.out.println("HEKKi");

            }*/
        }
        });
           toggleButton4.addEventToggleSelected(new ToggleAdapter(){
        public void onSelected(boolean selected){
           /* if(selected){
            System.out.println("SELECETED");
            }
                else{
                System.out.println("HEKKi");

            }*/
        }
        });
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonGradient1 = new swing.ButtonGradient();
        buttonGradient3 = new swing.ButtonGradient();
        buttonGradient4 = new swing.ButtonGradient();
        buttonGradient5 = new swing.ButtonGradient();
        buttonGradient7 = new swing.ButtonGradient();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        comboBoxSuggestion1 = new swing.ComboBoxSuggestion();
        comboBoxSuggestion2 = new swing.ComboBoxSuggestion();
        comboBoxSuggestion3 = new swing.ComboBoxSuggestion();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        sliderGradient3 = new swing.SliderGradient();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        sliderGradient4 = new swing.SliderGradient();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        toggleButton1 = new swing.ToggleButton();
        toggleButton2 = new swing.ToggleButton();
        toggleButton3 = new swing.ToggleButton();
        toggleButton4 = new swing.ToggleButton();
        buttonGradient6 = new swing.ButtonGradient();
        jPanel5 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        buttonGradient8 = new swing.ButtonGradient();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonGradient2 = new swing.ButtonGradient();
        jLabel27 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        buttonGradient11 = new swing.ButtonGradient();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        buttonGradient9 = new swing.ButtonGradient();
        jLabel30 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        buttonGradient10 = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGradient1.setText("LOGOUT");
        buttonGradient1.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient1.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient1.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGradient1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 150, -1));

        buttonGradient3.setText("SORT");
        buttonGradient3.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient3.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient3.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient3ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGradient3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 150, -1));

        buttonGradient4.setText("SHORTLIST");
        buttonGradient4.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient4.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient4.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient4ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGradient4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 150, -1));

        buttonGradient5.setText("COMPARE");
        buttonGradient5.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient5.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient5.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient5ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGradient5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 150, -1));

        buttonGradient7.setText("ACCOUNT");
        buttonGradient7.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient7.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient7.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient7ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGradient7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 150, -1));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 86));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, -1, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 439));

        jLabel2.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 102));
        jLabel2.setText("Presented in Power BI");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(jLabel2)
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(203, 203, 203))
        );

        jTabbedPane1.addTab("tab1", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));

        comboBoxSuggestion1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Wisconsin", "West Virginia", "Washington", "Virginia", "Vermont", "Utah", "Texas", "Tennessee", "South Dakota", "South Carolina", "Rhode Island", "Pennsylvania", "Oregon", "Oklahoma", "Ohio", "North Dakota", "North Carolina", "New York", "New Mexico", "New Jersey", "New Hampshire", "Nevada", "Nebraska", "Montana", "Missouri", "Mississippi", "Minnesota", "Michigan", "Massachusetts", "Maryland", "Louisiana", "Kentucky", "Kansas", "Iowa", "Indiana", "Illinois", "Idaho", "Hawaii", "Georgia", "Florida", "District of Columbia", "Delaware", "Connecticut", "Colorado", "California", "Arkansas", "Arizona", "Alaska", "Alabama", " " }));
        comboBoxSuggestion1.setSelectedIndex(-1);
        comboBoxSuggestion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSuggestion1ActionPerformed(evt);
            }
        });

        comboBoxSuggestion2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6" }));
        comboBoxSuggestion2.setSelectedIndex(-1);

        comboBoxSuggestion3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", " " }));
        comboBoxSuggestion3.setSelectedIndex(-1);
        comboBoxSuggestion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxSuggestion3ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 83, 121));
        jLabel4.setText("Room ");

        jLabel8.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 83, 121));
        jLabel8.setText("Floor");

        jLabel9.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("0");

        sliderGradient3.setBackground(new java.awt.Color(204, 204, 204));
        sliderGradient3.setForeground(new java.awt.Color(204, 204, 204));
        sliderGradient3.setMajorTickSpacing(10000);
        sliderGradient3.setMaximum(100000);
        sliderGradient3.setMinimum(500);
        sliderGradient3.setMinorTickSpacing(2000);
        sliderGradient3.setSnapToTicks(true);
        sliderGradient3.setToolTipText("");
        sliderGradient3.setValue(0);
        sliderGradient3.setColor1(new java.awt.Color(153, 153, 255));
        sliderGradient3.setColor2(new java.awt.Color(153, 255, 255));
        sliderGradient3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderGradient3StateChanged(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 83, 121));
        jLabel10.setText("Preferred Nearby Facilities");

        jLabel11.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 83, 121));
        jLabel11.setText("Max Price");

        sliderGradient4.setBackground(new java.awt.Color(204, 204, 204));
        sliderGradient4.setForeground(new java.awt.Color(204, 204, 204));
        sliderGradient4.setMajorTickSpacing(10000);
        sliderGradient4.setMaximum(600000);
        sliderGradient4.setMinimum(500);
        sliderGradient4.setMinorTickSpacing(2000);
        sliderGradient4.setSnapToTicks(true);
        sliderGradient4.setColor1(new java.awt.Color(153, 153, 255));
        sliderGradient4.setColor2(new java.awt.Color(153, 255, 255));
        sliderGradient4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderGradient4StateChanged(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 83, 121));
        jLabel12.setText("Min Price");

        jLabel13.setFont(new java.awt.Font("FreeSans", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 51, 102));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("0");

        jLabel15.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 83, 121));
        jLabel15.setText("State");

        jLabel19.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 83, 121));
        jLabel19.setText("Schools");

        jLabel20.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 83, 121));
        jLabel20.setText("Offices");

        jLabel21.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 83, 121));
        jLabel21.setText("Hospitals");

        jLabel22.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 83, 121));
        jLabel22.setText("Parks");

        toggleButton1.setForeground(new java.awt.Color(153, 153, 255));

        toggleButton2.setForeground(new java.awt.Color(133, 133, 235));

        toggleButton3.setForeground(new java.awt.Color(113, 113, 215));

        toggleButton4.setForeground(new java.awt.Color(75, 75, 183));

        buttonGradient6.setText("FILTER");
        buttonGradient6.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient6.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient6.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(toggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(87, 87, 87)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(toggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addGap(111, 111, 111))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(toggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(comboBoxSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel12)))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sliderGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(jLabel11))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(283, 283, 283)
                        .addComponent(buttonGradient6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(jLabel15)
                .addGap(231, 231, 231)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(91, 91, 91))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel4)))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboBoxSuggestion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSuggestion2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBoxSuggestion3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(sliderGradient3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(sliderGradient4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel9))
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toggleButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonGradient6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("tab2", jPanel3);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 440, 120, -1));

        jLabel5.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 102));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("MANAGEMENT TYPE");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 140, 20));
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 120, -1));

        jLabel6.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 102));
        jLabel6.setText("Enter Apartment ID 2");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 420, -1, -1));

        buttonGradient8.setText("ENTER");
        buttonGradient8.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient8.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient8.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient8ActionPerformed(evt);
            }
        });
        jPanel5.add(buttonGradient8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 110, 30));

        jLabel7.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Enter Apartment ID 1");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 420, -1, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setRowHeight(36);
        jScrollPane2.setViewportView(jTable2);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 230, 320));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Details"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable3.setRowHeight(36);
        jScrollPane3.setViewportView(jTable3);

        jPanel5.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 230, 320));

        jLabel14.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 102));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("PRICE");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 140, -1));

        jLabel16.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 102));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SIZE");
        jPanel5.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 140, 30));

        jLabel17.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("YEAR BUILT");
        jPanel5.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 140, 20));

        jLabel18.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 102));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("FLOOR");
        jPanel5.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 140, -1));

        jLabel23.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 102));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("HALLWAY TYPE");
        jPanel5.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 140, 20));

        jLabel24.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 102));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("NUMBER OF ROOMS");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 140, -1));

        jLabel25.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("HEATING TYPE");
        jPanel5.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 140, 20));

        jTabbedPane1.addTab("tab4", jPanel5);

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Apartment ID", "Address", "State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, 693, 350));

        buttonGradient2.setText("BUY");
        buttonGradient2.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient2.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient2.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient2ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonGradient2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 100, 30));

        jLabel27.setFont(new java.awt.Font("FreeSans", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 102));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Enter Apartment ID");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 140, -1));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 120, -1));

        buttonGradient11.setText("REFRESH");
        buttonGradient11.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient11.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient11.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient11ActionPerformed(evt);
            }
        });
        jPanel4.add(buttonGradient11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 100, 30));

        jTabbedPane1.addTab("tab3", jPanel4);

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setPreferredSize(new java.awt.Dimension(700, 439));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 102));
        jLabel26.setText("E-mail");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        jPanel6.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 40));

        buttonGradient9.setText("UPDATE");
        buttonGradient9.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient9.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient9.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient9ActionPerformed(evt);
            }
        });
        jPanel6.add(buttonGradient9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 150, -1));

        jLabel30.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 0, 102));
        jLabel30.setText("Last Name");
        jPanel6.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));
        jPanel6.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 280, 40));

        jLabel31.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 0, 102));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Property Shorlisted");
        jPanel6.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 180, -1));
        jPanel6.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 280, 40));
        jPanel6.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 280, 40));

        jLabel32.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 0, 102));
        jLabel32.setText("Phone Number");
        jPanel6.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel33.setFont(new java.awt.Font("FreeSans", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 102));
        jLabel33.setText("First Name");
        jPanel6.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        jLabel34.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("0");
        jPanel6.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 30, 20));

        jLabel35.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 102));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Property Owned");
        jPanel6.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 180, -1));

        jLabel36.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("0");
        jPanel6.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 30, 20));

        jLabel37.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 102));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Total Spent");
        jPanel6.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, 180, -1));

        jLabel38.setFont(new java.awt.Font("FreeSans", 0, 24)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("0");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, 120, 20));

        jTabbedPane1.addTab("tab1", jPanel6);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, -20, 730, 520));
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab1\n\n");

        buttonGradient10.setText("DASHBOARD");
        buttonGradient10.setColor1(new java.awt.Color(122, 165, 172));
        buttonGradient10.setColor2(new java.awt.Color(95, 104, 143));
        buttonGradient10.setFont(new java.awt.Font("FreeSans", 0, 12)); // NOI18N
        buttonGradient10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient10ActionPerformed(evt);
            }
        });
        jPanel1.add(buttonGradient10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeStatus(int i){
        String sql = "update apartment_details set status = sold where apartment_id =" + i;
        try{
            pst = conn.prepareStatement(sql);
            pst.executeQuery();
            JOptionPane.showMessageDialog(rootPane, "Status of the apartment has changed to Sold!");
        }
        
        catch(Exception e){
                
                }
    }
    private void buttonGradient2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient2ActionPerformed
        // TODO add your handling code here:
        UserInfo ui = new UserInfo();
        int ci = ui.getId();
        int ai = Integer.valueOf(jTextField4.getText());
        int li = Lease_id+1;
        
        try{
            st = conn.createStatement();
            String sql = "insert into Sale_details values('"+date+"', "+ci+", "+ai+", "+li+")";
            st.executeUpdate(sql);
            
            ChangeStatus(ci);
        }
        catch(Exception e){
            
        }  
       
    }//GEN-LAST:event_buttonGradient2ActionPerformed

    private void buttonGradient3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient3ActionPerformed
        // TODO add your handling code here:
      
        jTabbedPane1.setSelectedIndex(1);
        
        
        
        
    }//GEN-LAST:event_buttonGradient3ActionPerformed

    private void buttonGradient4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient4ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        selectList();
    }//GEN-LAST:event_buttonGradient4ActionPerformed

    private void buttonGradient5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient5ActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_buttonGradient5ActionPerformed

    private void sliderGradient3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderGradient3StateChanged
        // TODO add your handling code here:
        jLabel13.setText(sliderGradient3.getValue()+"");
    }//GEN-LAST:event_sliderGradient3StateChanged

    private void sliderGradient4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderGradient4StateChanged
        // TODO add your handling code here:
        jLabel9.setText(sliderGradient4.getValue()+"");
    }//GEN-LAST:event_sliderGradient4StateChanged

    private void comboBoxSuggestion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSuggestion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSuggestion1ActionPerformed

    private void buttonGradient6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient6ActionPerformed
        // TODO add your handling code here:
        int count =0;
        String sql = "Select * from apartment_details natural join apartment_facilities where state = '" + comboBoxSuggestion1.getSelectedItem() + "' and  Room_Num = " + comboBoxSuggestion2.getSelectedItem();
        sql = sql+ " And Floor = " + comboBoxSuggestion3.getSelectedItem() +" And SalePrice>= " + sliderGradient3.getValue()+ " And SalePrice <= " + sliderGradient4.getValue();
        
        if(toggleButton1.isSelected()){
            sql = sql + " And Hospital != 0";
        }
        if(toggleButton2.isSelected()){
            sql = sql + " And Middle_school != 0";
            
        }
        if(toggleButton3.isSelected()){
            sql = sql + " and PublicOffice != 0";
            
        }
        if(toggleButton4.isSelected()){
            sql = sql + " and Park !=0";
          
   
        }
        try{
            System.out.println(sql);
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            
            while(rs.next()){
            count++;
            }
            System.out.println(count);
            rs.close();
            ps.close();
            if(count == 0){
            JOptionPane.showMessageDialog(null, "No matches found- please try with different filters.");
         }
             else{
                 Buy b = new Buy(sql);
                 new Buy(sql).setVisible(true);
                
                 
                 
             
        }      
        }
       
        
    catch(Exception e){
            
            }
    }//GEN-LAST:event_buttonGradient6ActionPerformed

    private void setAccount(){
        UserInfo un= new UserInfo();
        int i = un.getId();
        String sql = "Select * from ccl where client_ID = " + i;
        
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            if(rs.next()){
                jTextField8.setText(rs.getString("first_name"));
                jTextField7.setText(rs.getString("last_name"));
                jTextField3.setText(rs.getString("email")); 
                jTextField9.setText(rs.getString("Phone_num"));
                if(rs.getString("tot_prop") == null){
                    jLabel36.setText("0");
                   
                }
                else{
                    jLabel36.setText(String.valueOf(rs.getInt("tot_prop")));
                    
                }
                if(rs.getString("tot_price") == null){
                     jLabel38.setText("0");
                }
                else{
                    jLabel38.setText(String.valueOf(rs.getInt("tot_price")));
                    
                }
                int co = countShort();
               jLabel34.setText(String.valueOf(co));
               
                
            }
            
            
        }
        catch(Exception e){
            
        }
    }
    private int countShort(){
        UserInfo un = new UserInfo();
        int i = un.getId();
        int n = 0;
        
        String sql = "Select count(Apartment_id) as tot from Short where Client_id = " + i;
        try{
        pst = conn.prepareStatement(sql);
        rs = pst.executeQuery();
            
        if(rs.next()){
            n = rs.getInt("tot");
            
        }
       
        
        }
        catch(Exception e){
            
        }
         return n;
        
    }
    
    private void selectList(){
        UserInfo un = new UserInfo();
        int i = un.getId();
        String sql = "select * from apartment_details natural join short where client_id = " + i;
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel tModel = (DefaultTableModel)jTable1.getModel();
            tModel.setRowCount(0);
            while(rs.next()){
                String ai = String.valueOf(rs.getString("Apartment_id"));
                String ad = rs.getString("Street_Add");
                String sc = rs.getString("State");
                String tData[] = {ai, ad, sc};
                tModel.addRow(tData);
                
            }
        }
        catch(Exception e){
            
        }
    }
    private void buttonGradient7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient7ActionPerformed
    jTabbedPane1.setSelectedIndex(4);    
    setAccount();
    
    }//GEN-LAST:event_buttonGradient7ActionPerformed

    private void fillTable1(String s){
        int i;
        int n = Integer.valueOf(s);
        String sql = "Select * from apartment_details where apartment_id = " + n;
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel tModel = (DefaultTableModel)jTable3.getModel();
            while(rs.next()){
                String p = String.valueOf(rs.getString(2));
                String sz = String.valueOf(rs.getString(4));
                String y = String.valueOf(rs.getString(3));
                String f = String.valueOf(rs.getString(5));
                String ht = rs.getString(6);
                String r = String.valueOf(rs.getString(7));
                String h = rs.getString(8);
                String m = rs.getString(9);
                String tData[] = {p, sz, y, f, ht, r, h, m};
                
                for(i=0; i<8; i++){
               
                    tModel.setValueAt(tData[i], i, 0);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }
    private void fillTable2(String s){
         int i;
        int n = Integer.valueOf(s);
        String sql = "Select * from apartment_details where apartment_id = " + n;
        try{
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            DefaultTableModel tModel = (DefaultTableModel)jTable2.getModel();
            while(rs.next()){
                String p = String.valueOf(rs.getString(2));
                String sz = String.valueOf(rs.getString(4));
                String y = String.valueOf(rs.getString(3));
                String f = String.valueOf(rs.getString(5));
                String ht = rs.getString(6);
                String r = String.valueOf(rs.getString(7));
                String h = rs.getString(8);
                String m = rs.getString(9);
                String tData[] = {p, sz, y, f, ht, r, h, m};
                
                for(i=0; i<8; i++){
               
                    tModel.setValueAt(tData[i], i, 0);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }
    
    private void buttonGradient8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient8ActionPerformed
        String s1 = jTextField1.getText();
        String s2 = jTextField2.getText();
        fillTable1(s1);
        fillTable2(s2);
        
    }//GEN-LAST:event_buttonGradient8ActionPerformed

    private void comboBoxSuggestion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxSuggestion3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboBoxSuggestion3ActionPerformed

    private void buttonGradient9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient9ActionPerformed
        // TODO add your handling code here:
        UserInfo ui = new UserInfo();
        int i = ui.getId();
        try{
            String sql ="update client_details set first_name = ?, last_name = ?, email = ? ,gender = ?, phone_num = ?, client_id = ?";
            pst = conn.prepareStatement(sql);
            pst.setString(2, jTextField8.getText());
            pst.setString(3, jTextField7.getText());
            pst.setString(4, jTextField3.getText());
            pst.setString(6, jTextField9.getText());
            pst.setString(5, "Male");
            pst.setString(1, String.valueOf(i));
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null, "Info updated!");
            
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, e);
        }
       
    }//GEN-LAST:event_buttonGradient9ActionPerformed

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed
new Client().setVisible(true);
            setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    private void buttonGradient10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGradient10ActionPerformed

    private void buttonGradient11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient11ActionPerformed
        // TODO add your handling code here:
        selectList();
    }//GEN-LAST:event_buttonGradient11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    
    
    private swing.SliderGradient sliderGradient1;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient buttonGradient1;
    private swing.ButtonGradient buttonGradient10;
    private swing.ButtonGradient buttonGradient11;
    private swing.ButtonGradient buttonGradient2;
    private swing.ButtonGradient buttonGradient3;
    private swing.ButtonGradient buttonGradient4;
    private swing.ButtonGradient buttonGradient5;
    private swing.ButtonGradient buttonGradient6;
    private swing.ButtonGradient buttonGradient7;
    private swing.ButtonGradient buttonGradient8;
    private swing.ButtonGradient buttonGradient9;
    private swing.ComboBoxSuggestion comboBoxSuggestion1;
    private swing.ComboBoxSuggestion comboBoxSuggestion2;
    private swing.ComboBoxSuggestion comboBoxSuggestion3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private swing.SliderGradient sliderGradient3;
    private swing.SliderGradient sliderGradient4;
    private swing.ToggleButton toggleButton1;
    private swing.ToggleButton toggleButton2;
    private swing.ToggleButton toggleButton3;
    private swing.ToggleButton toggleButton4;
    // End of variables declaration//GEN-END:variables
}
